# Codemagic — альтернатива GitHub Actions для сборки Flutter APK
# Регистрация: https://codemagic.io (бесплатный тариф)
# Подключите репо GitHub — сборка должна пройти без ошибок GradleBuildTime

workflows:
  android-apk:
    name: Build APK
    max_build_duration: 30
    instance_type: mac_mini_m2
    environment:
      flutter: stable
      groups:
        - default
    scripts:
      - name: Set up local.properties
        script: |
          echo "flutter.sdk=$HOME/programs/flutter" >> "$CM_BUILD_DIR/android/local.properties"
      - name: Get Flutter packages
        script: flutter pub get
      - name: Build APK
        script: flutter build apk --release
    artifacts:
      - build/app/outputs/flutter-apk/*.apk
      - build/app/outputs/flutter-apk/
